### ISSUE TITLE
Finch and Raven not creating their wps_output under /bird_name

### ISSUE THREAD

**Issue by tlvu** [bird-house/birdhouse-deploy#11]
Migrated from old PAVICS https://github.com/Ouranosinc/PAVICS/issues/151

Does not cause problem now but might cause problem later when we want to restrict access to some wps output from these birds (for privacy reason).  Older birds (flyingpigeon, mallefowl, ...) are following this schema.

See discusstion in https://github.com/Ouranosinc/PAVICS/pull/150#discussion_r305084199

**Comment by huard** [comment]
Has this been fixed with the cookie-cutter template update ?

**Comment by tlvu** [comment]
Nope.  It's a deployment config.  It's probably directly in here, unless pywps do not have that config yet or the config do not support giving a initially non-existing dir.

**Comment by huard** [comment]
@dbyrns Is this required for cowbird ?

**Comment by dbyrns** [comment]
Cowbird will not handle process outputs so the quick answer is no. On the other hand wps_outputs is served by nginx and thredds so the structure could be "visible". We better have something well organized. Permissions management may be harder also if everything is mixed under the same folder.
To fix this, you probably don't have to update the bird directly. Weaver has been "fixed" simply by updating the volume mount in compose by defining the bird name on the server side. See : https://github.com/bird-house/birdhouse-deploy/blob/feature/DAC-300-weaver-compose/birdhouse/components/weaver/default.env#L54

**Comment by dbyrns** [comment]
Thank you @tlvu, after some DM with you thursday, I agreeded that the wps_outputs volume is mounted under `${DATA_PERSIST_ROOT}` only in thredds and we cannot mix and match volume and direct bind mount. The best solution is therefore https://github.com/bird-house/birdhouse-deploy/pull/203 

I remembered talking about that with @fmigneault and we were saying that sharing the same volume with all birds is not a very good practice. Sadly some birds expect to create a directory having their bird name. Without that behavior having a named volume per-bird would have solved the issue and be a better practice by isolating each bird.

@fmigneault, after having talk with @tlvu I'm no longer confident that the solution used in Weaver will be correct. The direct bind mount `${DATA_PERSIST_ROOT}/wps_outputs/weaver` will probably not be exposed in thredds or nginx since the wps_outputs directory will be replaced by the volume mount. Will need to check that later (another PR 😉).

**Comment by fmigneault** [comment]
> This also means the current way Weaver tries to share it's wpsoutput is wrong since the Nginx proxy also use the data-volume

> The direct bind mount ${DATA_PERSIST_ROOT}/wps_outputs/weaver will probably not be exposed in thredds or nginx since the wps_outputs directory will be replaced by the volume mount. 

Not true. Have a try: https://host-140-154.rdext.crim.ca/wpsoutputs/weaver/2dd1d8ca-651c-4644-9ac6-b6bf32718457.log


> Without that behavior having a named volume per-bird would have solved the issue

I still believe the fix should be on the bird's side. Some flag to create or not the named directory. 
It should not enforce a specific name, and they should definitely remain distinct volumes.

**Comment by tlvu** [comment]
This is not yet working, update here https://github.com/bird-house/birdhouse-deploy/pull/231#issuecomment-1029133290
