### ISSUE TITLE
Feature Template and auto-labels

### ISSUE THREAD

**Issue by fmigneault** [bird-house/birdhouse-deploy#158]
Another amend related to `bird-house/contributions-guideline` (#156) that I discovered while writing this issue and the one in #157

There is no template for issues!!
One was introduced for PRs, but issues remain a blank canvas, which makes description of new ones either missing important details or not following any format to ease retrieval of details. 

A few things that I though could be important to define in the issue template: 

- type of issue (bug, proposition, feature, etc.?) 
- who does it concern ?  (a list of tagged users impacted by those changes)
- related issues, PR, components? 
- related build, environment, server URL, test suite

I think we should also take better advantage of labels. 
There are some currently employed (`bug`, `documentation`, `enhancement`, `question`), but they are added more or less based on good will. 
Issue template allows to define different template formats for different types of issues, and those can be associated with the corresponding tags. 

Same thing for the default title format. Some issues have `[Feature]`, other don't... The template can resolve this problem to make it more uniform, and the guidelines should reflect the use of those templates. 

@huard @tlvu @dbyrns @MatProv 
I would like to have your feedback and additional suggestion about other details I could have missed that could be needed in templates.

**Comment by dbyrns** [comment]
I guess you could copy/paste the one used in Magpie? Same apply for https://github.com/bird-house/birdhouse-deploy/issues/157 
I'm not against good templates as long as we can achieve this without too much work.

**Comment by huard** [comment]
No strong opinion. I often find myself deleting issue templates because my issue doesn't fit the format. 
Agree with need for clear labeling. 
I think we need 1-2 persons in charge of triage.

**Comment by fmigneault** [comment]
@huard 
I'm using this in Magpie to avoid this triage burden ;) 
https://github.com/Ouranosinc/Magpie/blob/master/.github/labeler.yml
https://github.com/Ouranosinc/Magpie/blob/master/.github/workflows/label.yml

@dbyrns 
I can write a first draft of the templates. Really not hard to define. I'm just poking to see if there are some info some of you believe are important and that I might have missed.

**Comment by tlvu** [comment]
Same as DavidH, I do not have strong opinion about template.  I also sometime just plain delete the whole generated template because the boilerplate text will just double what I need to express.

Most of the time, I will open an issue only if I will work on it later or if it will be for someone else.  If I will work on it immediately myself I will skip the issue and just open the PR.  The whole point is to minimize overhead.

I think if you can make it as simple and short as possible, user opening a new issue do not have to scroll too much to find the right section to put what they need to say then it would be the sweet spot of being organized without overwhelming the user and making the workflow harder for everything.

But I do see the usefulness if we have much more users opening issues.
