### ISSUE TITLE
:bug: [BUG]: `/components` endpoint is empty using auto-deploy

### ISSUE THREAD

**Issue by fmigneault** [bird-house/birdhouse-deploy#342]
## Details

The `/components` endpoint is empty after auto-deploy:

```json
{"components": []}
```

This does not happen when using `pavics-compose.sh`.

_Originally posted by @mishaschwartz in https://github.com/bird-house/birdhouse-deploy/issues/329#issuecomment-1591259721_

**Comment by mishaschwartz** [comment]
It looks like the issue is that `grep` in the `pavics/docker-compose-git:docker-18.09.7-compose-1.25.1` image does not support searching for multiple patterns that are separated by newlines (see: https://github.com/bird-house/birdhouse-deploy/blob/1.26.4/birdhouse/scripts/get-components-json.include.sh#L58-L59).

The fix would be to replace `BIRDHOUSE_DEPLOY_COMPONENTS_LIST_KNOWN` which currently looks like:

```
components/cowbird
components/monitoring
components/scheduler
components/weaver
config/canarie-api
... etc.
```

with 

```
-e components/cowbird -e components/monitoring -e components/scheduler -e components/weaver -e config/canarie-api
```

which should work with all versions of `grep`. 

I can make this change shortly.
